/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Chen
 */
public class Configurations extends javax.swing.JFrame {

    /**
     * Creates new form Configurations
     */
    public Configurations() {
        initComponents();
        Dimension dim = (Toolkit.getDefaultToolkit()).getScreenSize();
        setSize(dim);
        JFrame frame = new JFrame();
        frame.setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CEUnbypassed = new javax.swing.JButton();
        CEBypassed = new javax.swing.JButton();
        VDUnbypassed = new javax.swing.JButton();
        EF = new javax.swing.JButton();
        FB = new javax.swing.JButton();
        CB = new javax.swing.JButton();
        CF = new javax.swing.JButton();
        VDBypassed = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(null);

        CEUnbypassed.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        CEUnbypassed.setText("Common Emitter Unbypassed");
        jPanel1.add(CEUnbypassed);
        CEUnbypassed.setBounds(190, 250, 240, 50);

        CEBypassed.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        CEBypassed.setText("Common Emitter Bypassed");
        jPanel1.add(CEBypassed);
        CEBypassed.setBounds(190, 350, 240, 40);

        VDUnbypassed.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        VDUnbypassed.setText("Voltage Divider Unbypassed");
        VDUnbypassed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VDUnbypassedActionPerformed(evt);
            }
        });
        jPanel1.add(VDUnbypassed);
        VDUnbypassed.setBounds(550, 250, 230, 42);

        EF.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        EF.setText("Emitter Follower");
        jPanel1.add(EF);
        EF.setBounds(190, 450, 240, 42);

        FB.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        FB.setText("Fixed Bias");
        jPanel1.add(FB);
        FB.setBounds(880, 250, 240, 42);

        CB.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        CB.setText("Common Base");
        CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBActionPerformed(evt);
            }
        });
        jPanel1.add(CB);
        CB.setBounds(880, 340, 240, 42);

        CF.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        CF.setText("Collector Feedback");
        jPanel1.add(CF);
        CF.setBounds(540, 450, 230, 42);

        VDBypassed.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        VDBypassed.setText("Voltage Divider Bypassed");
        VDBypassed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VDBypassedActionPerformed(evt);
            }
        });
        jPanel1.add(VDBypassed);
        VDBypassed.setBounds(880, 440, 240, 42);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(510, 670, 290, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1356, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VDUnbypassedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VDUnbypassedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VDUnbypassedActionPerformed

    private void CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBActionPerformed

    private void VDBypassedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VDBypassedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VDBypassedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configurations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configurations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configurations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configurations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configurations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CB;
    private javax.swing.JButton CEBypassed;
    private javax.swing.JButton CEUnbypassed;
    private javax.swing.JButton CF;
    private javax.swing.JButton EF;
    private javax.swing.JButton FB;
    private javax.swing.JButton VDBypassed;
    private javax.swing.JButton VDUnbypassed;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
