package tulongko;

import eceproject.*;
import proto2.*;
import javax.swing.*;
import java.util.Scanner;
import java.awt.Cursor;

public class twoportsystem extends javax.swing.JFrame {
    
    public static int sysno;
    public static twoport[] tp;
    
    public twoportsystem(int sysno,twoport[] tp) {
//        ConfigurationsCom cc = new ConfigurationsCom();
//        cc.initialize();
        this.tp = tp;
        this.sysno=sysno;
        initComponents();
        int counter = 0, labelindex = 0, configindex = 0,xdistance=0;
        javax.swing.JLabel[] configs = new JLabel[sysno];
        javax.swing.JLabel[] configlabels = new JLabel[sysno];
        javax.swing.JLabel[] avlabels = new JLabel[sysno];
        javax.swing.JLabel[] zilabels = new JLabel[sysno];
        javax.swing.JLabel[] zolabels = new JLabel[sysno];
        final Configurations[] c = new Configurations[sysno];
//        ConfigurationsCom cc = new ConfigurationsCom();
//        cc.number= sysno;
        
        while (counter < sysno) {
            final int sno = configindex;
            
            // For labels of the configs
            configlabels[labelindex] = new JLabel("System " + (labelindex + 1));
            configlabels[labelindex].setSize(110, 80);
            configlabels[labelindex].setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            configlabels[labelindex].setLocation(140 + xdistance, 80);
            configlabels[labelindex].setVisible(true);
            jPanel2.add(configlabels[labelindex]);
            avlabels[labelindex] = new JLabel("Av = "+tp[labelindex].Av);
            avlabels[labelindex].setSize(110, 30);
            avlabels[labelindex].setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            avlabels[labelindex].setLocation(140 + xdistance, 160);
            avlabels[labelindex].setVisible(true);
            jPanel2.add(avlabels[labelindex]);
            zilabels[labelindex] = new JLabel("Zi = "+tp[labelindex].Zi);
            zilabels[labelindex].setSize(110, 50);
            zilabels[labelindex].setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            zilabels[labelindex].setLocation(140 + xdistance, 160);
            zilabels[labelindex].setVisible(true);
            jPanel2.add(zilabels[labelindex]);
            zolabels[labelindex] = new JLabel("Zo = "+tp[labelindex].Zi);
            zolabels[labelindex].setSize(110, 70);
            zolabels[labelindex].setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            zolabels[labelindex].setLocation(140 + xdistance, 160);
            zolabels[labelindex].setVisible(true);
            jPanel2.add(zolabels[labelindex]);
            
            // For two port configs
            configs[configindex] = new JLabel();
            configs[configindex].setIcon(new ImageIcon(twoportsystem.class.getResource("/tulongko/twoportedited.png")));
            configs[configindex].setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            configs[configindex].setLocation(50 + xdistance, 80);

            configs[configindex].setSize(375, 260);
            configs[configindex].setVisible(true);
            jPanel2.add(configs[configindex]);
//            void configs(java.awt.event.MouseEvent evt) {                                     
//             // TODO add your handling code here:
//            }
            configs[configindex].addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
//                jButton1MouseEntered(evt);
                    JOptionPane.showMessageDialog(null, "BJT Configuration pressed!", "Information Message", JOptionPane.INFORMATION_MESSAGE);
                    c[sno] = new Configurations();
//                    ConfigurationsCom cc = new ConfigurationsCom();
                    c[sno].setSize(1500, 1000);
                    c[sno].sysno = sno;
                    System.out.println(sno);
//                    cc.number = sno;

                    c[sno].setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
                    c[sno].setVisible(true);

                }

            });
            xdistance += (380);

//            System.out.println("JLabel Created");
            jPanel2.repaint();
            labelindex++;
            configindex++;
            counter++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jButton1.setText("Back");
        jPanel2.add(jButton1);
        jButton1.setBounds(1170, 380, 80, 40);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jButton2.setText("Simulate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(1060, 380, 80, 40);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 36)); // NOI18N
        jLabel1.setText("Cascaded System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1278, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(492, 492, 492)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ConfigurationsCom cc = new ConfigurationsCom();
        cc.AvLoaded();
        cc.CascadedValues();

        String effects = "[1] Effects of Rs\n[2]Effects of RL\n[3]Combined Effects of Rs and RL";
        String effectChoice = JOptionPane.showInputDialog("Choose effect on cascaded system\n" + effects);
        boolean condition = false;
        do {
            switch (effectChoice) {
                case "1":
                    double sourceVoltage = Double.parseDouble(JOptionPane.showInputDialog(null, "Enter input voltage"));
                    cc.sourceVoltage = sourceVoltage;
                    double Rsense = Double.parseDouble(JOptionPane.showInputDialog(null, "Enter Rsense "));
                    cc.Rsense = Rsense;
                    cc.EffectsOfRS();
                    condition = true;
                    break;
                case "2":
                    sourceVoltage = Double.parseDouble(JOptionPane.showInputDialog(null, "Enter input voltage"));
                    cc.inputVoltage = sourceVoltage;
                    double RLoad = Double.parseDouble(JOptionPane.showInputDialog(null, "Enter RLoad "));
                    cc.RLoad = RLoad;

                    cc.EffectsOfRL();
                    condition = true;
                    break;
//                case "3":
//                    
//                    cc.condition = true; 
//                    break;
                default:
                    System.out.println("Invalid input!");
                    continue;
            }
        } while (condition != true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new twoportsystem(sysno,tp).setVisible(true);
            }
        });
//        Balikan maya

        System.out.println("Test");
//        int xdistance = 0;
//        JScrollPane jScrollPane = new JScrollPane(jPanel2);
//        // only a configuration to the jScrollPane...
//        jScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
//        jScrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        // Then, add the jScrollPane to your frame
//        javax.swing.JLabel bjt1=new JLabel();
//        bjt1.setIcon(new ImageIcon(twoportsystem.class.getResource("/tulongko/twoportedited.png")));
//        bjt1.setLocation(50, 80);
//        bjt1.setSize(370,260);
//        bjt1.setVisible(true);
//        javax.swing.JLabel bjt1label=new JLabel();
//        bjt1label.setLocation(190, 120);
//        bjt1label.setSize(120,100);
//        bjt1label.setVisible(true);
//        jPanel2.add(bjt1label);
//        jPanel2.add(bjt1);
//        System.out.println("Components loaded..");
//        String config = JOptionPane.showInputDialog("Enter bjt configuration:");
//        bjt1label.setText(config);
//        
//        javax.swing.JLabel bjt2=new JLabel();
//        bjt2.setIcon(new ImageIcon(twoportsystem.class.getResource("/tulongko/twoportedited.png")));
//        bjt2.setLocation(50+380, 80);
//        bjt2.setSize(370,260);
//        bjt2.setVisible(true);
//        javax.swing.JLabel bjt2label=new JLabel();
//        bjt2label.setLocation(190+330, 120);
//        bjt2label.setSize(120,100);
//        bjt2label.setVisible(true);
//        jPanel2.add(bjt2label);
//        jPanel2.add(bjt2);
//        System.out.println("Components loaded..");
//        config = JOptionPane.showInputDialog("Enter bjt configuration:");
//        bjt2label.setText(config);
//        ConfigurationsCom cc = new ConfigurationsCom();
//        System.out.println("Sysno is: "+sysno);
//        int sysno = Integer.parseInt(JOptionPane.showInputDialog("Enter the number of systems: "));

//        int counter = 0, labelindex = 0, configindex = 0;
//        javax.swing.JLabel[] configs = new JLabel[sysno];
//        javax.swing.JLabel[] configlabels = new JLabel[sysno];
//        final Configurations[] c = new Configurations[sysno];
////        ConfigurationsCom cc = new ConfigurationsCom();
////        cc.number= sysno;
//        
//        while (counter < sysno) {
//            final int sno = configindex;
//            
//            // For labels of the configs
//            configlabels[labelindex] = new JLabel("System " + (labelindex + 1));
//            configlabels[labelindex].setSize(100, 80);
//            configlabels[labelindex].setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
//            configlabels[labelindex].setLocation(140 + xdistance, 100);
//            configlabels[labelindex].setVisible(true);
//            jPanel2.add(configlabels[labelindex]);
//
//            // For two port configs
//            configs[configindex] = new JLabel();
//            configs[configindex].setIcon(new ImageIcon(twoportsystem.class.getResource("/tulongko/twoportedited.png")));
//            configs[configindex].setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
//            configs[configindex].setLocation(50 + xdistance, 80);
//
//            configs[configindex].setSize(370, 260);
//            configs[configindex].setVisible(true);
//            jPanel2.add(configs[configindex]);
////            void configs(java.awt.event.MouseEvent evt) {                                     
////             // TODO add your handling code here:
////            }
//            configs[configindex].addMouseListener(new java.awt.event.MouseAdapter() {
//                public void mousePressed(java.awt.event.MouseEvent evt) {
////                jButton1MouseEntered(evt);
//                    JOptionPane.showMessageDialog(null, "BJT Configuration pressed!", "Information Message", JOptionPane.INFORMATION_MESSAGE);
//                    c[sno] = new Configurations();
////                    ConfigurationsCom cc = new ConfigurationsCom();
//                    c[sno].setSize(1500, 1000);
//                    c[sno].sysno = sno;
//                    System.out.println(sno);
////                    cc.number = sno;
//
//                    c[sno].setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
//                    c[sno].setVisible(true);
//
//                }
//
//            });
//            xdistance += (350);
//
////            System.out.println("JLabel Created");
//            jPanel2.repaint();
//            labelindex++;
//            configindex++;
//            counter++;
//        }

//        int counter=0,jlabellength=sysno*2,labelindex=0,configindex=0;
//        javax.swing.JLabel[] configs=new JLabel[jlabellength];
//        while(counter<sysno){
//            System.out.println(counter<sysno);
//            // Code for initiating the two port picture
//            configs[labelindex]=new JLabel();
//            configs[labelindex].setIcon(new ImageIcon(twoportsystem.class.getResource("/tulongko/twoportedited.png")));
//            configs[labelindex].setLocation(50+xdistance, 80);
//            configs[labelindex].setSize(370,260);
//            configs[labelindex].setVisible(true);
//            
//            labelindex++;
//            
//            // code for initiating the description
////            javax.swing.JLabel bjt1label=new JLabel();
//            configs[labelindex]=new JLabel();
//            configs[labelindex].setLocation(190, 120);
//            configs[labelindex].setSize(120,100);
//            configs[labelindex].setVisible(true);
////            jPanel2.add(bjt1label);
////            jPanel2.add(bjt1);
//            jPanel2.add(configs[labelindex]);
//            jPanel2.add(configs[configindex]);
//            System.out.println("Components loaded..");
//            String config = JOptionPane.showInputDialog("Enter bjt configuration:");
//            configs[labelindex].setText(config); 
//            xdistance+=300;
//            labelindex++;
//            configindex++;
//            counter++;
//        }
    }

//    private void jButton1MouseExited(java.awt.event.ActionEvent evt){
//        JOptionPane.showMessageDialog(null, "Exited Ready to Work!");
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
