package eceproject;

import javax.swing.JOptionPane;
import proto2_backup.Voltagedivider_bypassed;
import tulongko.*;

public class Ro_Voltage_Divider extends javax.swing.JFrame {

    public double VCCval, R1val, R2val, BETAval, RCval, REval;
    ConfigurationsCom cc = new ConfigurationsCom();
    public static int sysno;

    /**
     * Creates new form Voltage_Divider
     */
    public Ro_Voltage_Divider() {
//        sysno = systemno;
//        System.out.println("This is system "+sysno);
//        JOptionPane.showMessageDialog(null, "This is system "+sysno);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        DCAnalysis = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        VDRTH = new javax.swing.JTextField();
        VDETH = new javax.swing.JTextField();
        VDIE = new javax.swing.JTextField();
        VDIC = new javax.swing.JTextField();
        VDVCE = new javax.swing.JTextField();
        DCequiv = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        VDRC = new javax.swing.JLabel();
        RC = new javax.swing.JTextField();
        VDR1 = new javax.swing.JLabel();
        R1 = new javax.swing.JTextField();
        VDR2 = new javax.swing.JLabel();
        R2 = new javax.swing.JTextField();
        VDRE = new javax.swing.JLabel();
        RE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        VCC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Beta = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        ACAnalysis = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        VDre = new javax.swing.JTextField();
        VDZi = new javax.swing.JTextField();
        VDZo = new javax.swing.JTextField();
        VDAv = new javax.swing.JTextField();
        VDAi = new javax.swing.JTextField();
        reModel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        VDBack = new javax.swing.JButton();
        VDOk = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 36)); // NOI18N
        jLabel1.setText("Voltage Divider (Bypassed)");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        DCAnalysis.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        DCAnalysis.setForeground(new java.awt.Color(255, 255, 255));
        DCAnalysis.setText("DC Analysis");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rth =");

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Eth = VR2 =");

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("IB =");

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("VCE =");

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("IC =");

        VDRTH.setEditable(false);

        VDETH.setEditable(false);

        VDIE.setEditable(false);

        VDIC.setEditable(false);

        VDVCE.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(DCAnalysis)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VDIE, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VDETH, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VDRTH, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(VDVCE, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(85, 85, 85)
                                        .addComponent(VDIC, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(20, 20, 20))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DCAnalysis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(VDRTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VDETH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VDIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VDIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VDVCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        DCequiv.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        DCequiv.setText("DC Equivalent Circuit");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elecs2guipics/voltagedividerDC.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(DCequiv))
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(DCequiv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(20, 260, 470, 240);

        VDRC.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        VDRC.setText("RC =");
        jPanel2.add(VDRC);
        VDRC.setBounds(610, 50, 40, 15);

        RC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(RC);
        RC.setBounds(610, 70, 90, 20);

        VDR1.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        VDR1.setText("R1 =");
        jPanel2.add(VDR1);
        VDR1.setBounds(450, 70, 29, 15);

        R1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(R1);
        R1.setBounds(410, 90, 90, 20);

        VDR2.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        VDR2.setText("R2 =");
        jPanel2.add(VDR2);
        VDR2.setBounds(450, 170, 40, 15);

        R2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(R2);
        R2.setBounds(410, 190, 90, 20);

        VDRE.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        VDRE.setText("RE =");
        jPanel2.add(VDRE);
        VDRE.setBounds(660, 170, 40, 14);

        RE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(RE);
        RE.setBounds(660, 190, 90, 20);

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel2.setText("VCC =");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(580, 10, 50, 15);

        VCC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        VCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VCCActionPerformed(evt);
            }
        });
        jPanel2.add(VCC);
        VCC.setBounds(620, 10, 60, 20);

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel3.setText("Beta=");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(620, 130, 50, 15);

        Beta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Beta);
        Beta.setBounds(660, 130, 90, 20);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        ACAnalysis.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        ACAnalysis.setForeground(new java.awt.Color(255, 255, 255));
        ACAnalysis.setText("AC Analysis");

        jLabel14.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("re =");

        jLabel15.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Zi =");

        jLabel16.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Zo =");

        jLabel17.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ai =");

        jLabel18.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Av =");

        VDre.setEditable(false);

        VDZi.setEditable(false);

        VDZo.setEditable(false);

        VDAv.setEditable(false);

        VDAi.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ACAnalysis)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(38, 38, 38))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(41, 41, 41)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(VDAi, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(VDAv)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(VDZo, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(VDZi)
                                    .addComponent(VDre))))
                        .addGap(20, 20, 20))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ACAnalysis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(VDre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VDZi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VDZo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VDAv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VDAi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        reModel.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        reModel.setText("re model");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elecs2guipics/AC_VoltageDividerre.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reModel)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(reModel)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel12))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(500, 260, 640, 230);

        VDBack.setBackground(new java.awt.Color(0, 153, 153));
        VDBack.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        VDBack.setText("Back");
        jPanel2.add(VDBack);
        VDBack.setBounds(1070, 520, 73, 23);

        VDOk.setBackground(new java.awt.Color(0, 153, 153));
        VDOk.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        VDOk.setText("Ok");
        VDOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VDOkActionPerformed(evt);
            }
        });
        jPanel2.add(VDOk);
        VDOk.setBounds(990, 520, 70, 23);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elecs2guipics/Voltage_Divider.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(420, -30, 280, 320);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(335, 335, 335))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VDOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VDOkActionPerformed
////        cc.value = sysno;
//        System.out.println("sysno:" + sysno);
//        System.out.println("VCC: " + VCC.getText());
//        System.out.println("sysno " + sysno);
//        cc.VCC[sysno] = Double.parseDouble(VCC.getText());
//        System.out.println("VCC:" + cc.VCC[sysno]);
//        cc.R1 = Double.parseDouble(R1.getText());
//        System.out.println("R1: " + cc.R1);
//        cc.R2 = Double.parseDouble(R2.getText());
//        System.out.println("R2: " + cc.R2);
//        cc.alphabet[sysno] = Double.parseDouble(Beta.getText());
//        System.out.println("Beta: " + cc.alphabet[sysno]);
//        cc.RC[sysno] = Double.parseDouble(RC.getText());
//        System.out.println("RC: " + cc.RC[sysno]);
//        cc.RE[sysno] = Double.parseDouble(RE.getText());
//        System.out.println("RE: " + cc.RE[sysno]);
//        cc.VoltageDividerBypassed();
        VCCval = Double.parseDouble(VCC.getText());
        R1val = Double.parseDouble(R1.getText());
        R2val = Double.parseDouble(R2.getText());
        BETAval = Double.parseDouble(Beta.getText());
        RCval = Double.parseDouble(RC.getText());
        REval = Double.parseDouble(RE.getText());
        this.dispose();
//        getValues();
           
    }//GEN-LAST:event_VDOkActionPerformed
//    public double VCCval, R1val, R2val, BETAval, RCval, REval;

    public void getValues() {
        VCCval = Double.parseDouble(VCC.getText());
        R1val = Double.parseDouble(R1.getText());
        R2val = Double.parseDouble(R2.getText());
        BETAval = Double.parseDouble(Beta.getText());
        RCval = Double.parseDouble(RC.getText());
        REval = Double.parseDouble(RE.getText());
        Voltagedivider_bypassed vdivider = new Voltagedivider_bypassed(VCCval, R1val, R2val, RCval, REval, BETAval);
        System.out.println("re is " + vdivider.getre());
    }
    private void VCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VCCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ro_Voltage_Divider().setVisible(true);
            }
        });

//        jLabel1.setText("VDivider Byp");
//        String desc=jLabel1.getText();
//        jLabel1.setText(desc+" System "+Integer.toString(sysno));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACAnalysis;
    private javax.swing.JTextField Beta;
    private javax.swing.JLabel DCAnalysis;
    private javax.swing.JLabel DCequiv;
    private javax.swing.JTextField R1;
    private javax.swing.JTextField R2;
    private javax.swing.JTextField RC;
    private javax.swing.JTextField RE;
    private javax.swing.JTextField VCC;
    private javax.swing.JTextField VDAi;
    private javax.swing.JTextField VDAv;
    private javax.swing.JButton VDBack;
    private javax.swing.JTextField VDETH;
    private javax.swing.JTextField VDIC;
    private javax.swing.JTextField VDIE;
    public javax.swing.JButton VDOk;
    private javax.swing.JLabel VDR1;
    private javax.swing.JLabel VDR2;
    private javax.swing.JLabel VDRC;
    private javax.swing.JLabel VDRE;
    private javax.swing.JTextField VDRTH;
    private javax.swing.JTextField VDVCE;
    private javax.swing.JTextField VDZi;
    private javax.swing.JTextField VDZo;
    private javax.swing.JTextField VDre;
    private static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel reModel;
    // End of variables declaration//GEN-END:variables
}
